In [10]:
import polars as pl
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
from UnifacDortmund import UnifacDortmund
from PhaseCalculation import CalculateComps as cc

In [2]:
group_contribution = pl.read_csv("SensitivityAnalysis/sensitivity_group_contribution.csv")
MW = pl.read_csv("SensitivityAnalysis/sensitivity_MW.csv")
coeffs = pl.read_csv("SensitivityAnalysis/sensitivity_params.csv")

In [3]:
group_contribution

shape: (784, 10)
┌───────────┬──────────┬─────────┬───────────┬───┬───────────┬─────┬─────────┬──────┐
│ FAME/FAEE ┆ GLYCEROL ┆ ALCOHOL ┆ OIL       ┆ … ┆ ACID      ┆ H2O ┆ Group   ┆ Stat │
│ ---       ┆ ---      ┆ ---     ┆ ---       ┆   ┆ ---       ┆ --- ┆ ---     ┆ ---  │
│ f64       ┆ f64      ┆ f64     ┆ f64       ┆   ┆ f64       ┆ f64 ┆ str     ┆ str  │
╞═══════════╪══════════╪═════════╪═══════════╪═══╪═══════════╪═════╪═════════╪══════╡
│ 0.0       ┆ 1.0      ┆ 0.0     ┆ 1.0       ┆ … ┆ 0.0       ┆ 0.0 ┆ Coconut ┆ min  │
│ 10.499156 ┆ 2.0      ┆ 0.0     ┆ 33.497469 ┆ … ┆ 10.499156 ┆ 0.0 ┆ Coconut ┆ min  │
│ 2.0       ┆ 0.0      ┆ 1.0     ┆ 3.0       ┆ … ┆ 1.0       ┆ 0.0 ┆ Coconut ┆ min  │
│ 0.119954  ┆ 0.0      ┆ 0.0     ┆ 0.359862  ┆ … ┆ 0.119954  ┆ 0.0 ┆ Coconut ┆ min  │
│ 0.0       ┆ 3.0      ┆ 1.0     ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0 ┆ Coconut ┆ min  │
│ …         ┆ …        ┆ …       ┆ …         ┆ … ┆ …         ┆ …   ┆ …       ┆ …    │
│ 1.06632   ┆ 0.0      ┆ 0.0     ┆ 3.198959  ┆ … ┆ 1.06632   ┆ 0.0 ┆ Peanut  ┆ mean │
│ 0.0       ┆ 3.0      ┆ 1.0     ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0 ┆ Peanut  ┆ mean │
│ 1.0       ┆ 0.0      ┆ 0.0     ┆ 3.0       ┆ … ┆ 0.0       ┆ 0.0 ┆ Peanut  ┆ mean │
│ 0.0       ┆ 0.0      ┆ 0.0     ┆ 0.0       ┆ … ┆ 1.0       ┆ 0.0 ┆ Peanut  ┆ mean │
│ 0.0       ┆ 0.0      ┆ 0.0     ┆ 0.0       ┆ … ┆ 0.0       ┆ 1.0 ┆ Peanut  ┆ mean │
└───────────┴──────────┴─────────┴───────────┴───┴───────────┴─────┴─────────┴──────┘

In [4]:
MW

shape: (98, 10)
┌────────────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬────────┐
│ group      ┆ stat   ┆ MW_FAME/FA ┆ MW_Glycero ┆ … ┆ MW_DAG     ┆ MW_MAG     ┆ MW_FA     ┆ MW_H2O │
│ ---        ┆ ---    ┆ EE         ┆ l          ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---    │
│ str        ┆ str    ┆ ---        ┆ ---        ┆   ┆ f64        ┆ f64        ┆ f64       ┆ i64    │
│            ┆        ┆ f64        ┆ f64        ┆   ┆            ┆            ┆           ┆        │
╞════════════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪════════╡
│ Grape Seed ┆ mean   ┆ 307.073169 ┆ 92.09      ┆ … ┆ 625.146338 ┆ 333.073169 ┆ 279.07316 ┆ 18     │
│            ┆        ┆            ┆            ┆   ┆            ┆            ┆ 9         ┆        │
│ Rapeseed   ┆ mean   ┆ 305.837765 ┆ 92.09      ┆ … ┆ 622.67553  ┆ 331.837765 ┆ 277.83776 ┆ 18     │
│            ┆        ┆            ┆            ┆   ┆            ┆            ┆ 5         ┆        │
│ Chicha     ┆ mean   ┆ 305.611285 ┆ 92.09      ┆ … ┆ 622.222569 ┆ 331.611285 ┆ 277.61128 ┆ 18     │
│            ┆        ┆            ┆            ┆   ┆            ┆            ┆ 5         ┆        │
│ Triolein   ┆ mean   ┆ 310.0      ┆ 92.09      ┆ … ┆ 631.0      ┆ 336.0      ┆ 282.0     ┆ 18     │
│ Linseed    ┆ mean   ┆ 305.816573 ┆ 92.09      ┆ … ┆ 622.633145 ┆ 331.816573 ┆ 277.81657 ┆ 18     │
│            ┆        ┆            ┆            ┆   ┆            ┆            ┆ 3         ┆        │
│ …          ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …      │
│ Rice Bran  ┆ mean   ┆ 303.813132 ┆ 92.09      ┆ … ┆ 618.626265 ┆ 329.813132 ┆ 275.81313 ┆ 18     │
│            ┆        ┆            ┆            ┆   ┆            ┆            ┆ 2         ┆        │
│ Jatropha   ┆ min    ┆ 302.688776 ┆ 92.09      ┆ … ┆ 616.377552 ┆ 328.688776 ┆ 274.68877 ┆ 18     │
│            ┆        ┆            ┆            ┆   ┆            ┆            ┆ 6         ┆        │
│ Jatropha   ┆ median ┆ 305.268101 ┆ 92.09      ┆ … ┆ 621.536203 ┆ 331.268101 ┆ 277.26810 ┆ 18     │
│            ┆        ┆            ┆            ┆   ┆            ┆            ┆ 1         ┆        │
│ Jatropha   ┆ max    ┆ 307.847426 ┆ 92.09      ┆ … ┆ 626.694853 ┆ 333.847426 ┆ 279.84742 ┆ 18     │
│            ┆        ┆            ┆            ┆   ┆            ┆            ┆ 6         ┆        │
│ Jatropha   ┆ mean   ┆ 305.268101 ┆ 92.09      ┆ … ┆ 621.536203 ┆ 331.268101 ┆ 277.26810 ┆ 18     │
│            ┆        ┆            ┆            ┆   ┆            ┆            ┆ 1         ┆        │
└────────────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴────────┘

In [5]:
coeffs

shape: (98, 6)
┌────────────┬────────┬───────────┬──────────┬─────┬─────┐
│ group      ┆ stat   ┆ m         ┆ n        ┆ p   ┆ b   │
│ ---        ┆ ---    ┆ ---       ┆ ---      ┆ --- ┆ --- │
│ str        ┆ str    ┆ f64       ┆ f64      ┆ f64 ┆ i64 │
╞════════════╪════════╪═══════════╪══════════╪═════╪═════╡
│ Grape Seed ┆ mean   ┆ 12.773231 ┆ 1.547998 ┆ 0.0 ┆ 0   │
│ Rapeseed   ┆ mean   ┆ 13.133518 ┆ 1.306481 ┆ 0.0 ┆ 0   │
│ Chicha     ┆ mean   ┆ 14.352474 ┆ 0.641409 ┆ 0.0 ┆ 0   │
│ Triolein   ┆ mean   ┆ 14.0      ┆ 1.0      ┆ 0.0 ┆ 0   │
│ Linseed    ┆ mean   ┆ 11.78236  ┆ 2.033213 ┆ 0.0 ┆ 0   │
│ …          ┆ …      ┆ …         ┆ …        ┆ …   ┆ …   │
│ Rice Bran  ┆ mean   ┆ 13.28067  ┆ 1.149375 ┆ 0.0 ┆ 0   │
│ Jatropha   ┆ min    ┆ 13.172086 ┆ 1.164599 ┆ 0.0 ┆ 0   │
│ Jatropha   ┆ median ┆ 13.249312 ┆ 1.222221 ┆ 0.0 ┆ 0   │
│ Jatropha   ┆ max    ┆ 13.326538 ┆ 1.279842 ┆ 0.0 ┆ 0   │
│ Jatropha   ┆ mean   ┆ 13.249312 ┆ 1.222221 ┆ 0.0 ┆ 0   │
└────────────┴────────┴───────────┴──────────┴─────┴─────┘

#### 1. Parametros UNIFAC Dortmund

In [6]:
params = np.loadtxt(r"C:\Juan\Maestría\Code\oleosim\Evaluation\Stochastic_optimization\GA\UDortmundParamsGARun1.out")

In [13]:
params
A = params[0:30]
B = params[30:60]
C = params[60:90]
    
GIP = cc.define_GIP(A, B, C)

thermo_model = UnifacDortmund

#### 2. Biodiesel, Glycerol, Alcohol

In [42]:
global_comps = np.array([0.824, 0.081, 0.095, 0, 0, 0, 0, 0]).reshape(1, 8)

In [33]:

def analysis_one(global_comps, MW, v, T):
    
    return (cc.calculate_comps(data=global_comps, v=v, data_MW=MW, 
                         temperature=T, thermo_model=thermo_model, GIP=GIP))

In [24]:
group_test = group_contribution.filter(
    (pl.col("Group") == "Grape Seed") & (pl.col("Stat") == "mean")
)

group_test = group_test.drop(["Group", "Stat"]).to_numpy()

In [36]:
MW_test = MW.filter(
    (pl.col("group") == "Grape Seed") & (pl.col("stat") == "mean")
) 


MW_test = MW_test.drop(["group", "stat"]).to_numpy().reshape(8)

In [43]:
analysis_one(global_comps=global_comps, MW=MW_test, v=group_test, T=298)

array([[9.99998044e-01, 4.60228873e-07, 2.31086702e-06, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        9.99998044e-07, 4.60228873e-01, 5.39766313e-01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])