In [2]:
import polars as pl
import numpy as np
from sklearn.metrics import root_mean_squared_error

In [10]:
def load_real_data(path):
    exp_data = pl.read_excel(path, engine="calamine")
    exp_compositions = exp_data.select([ 'FAME/FAEE_L', 'GLYCEROL_L', 'ALCOHOL_L', 'OIL_L', 'DAG_L', 'MAG_L', 'ACID_L', 'WATER_L', 'FAME/FAEE_H', 'GLYCEROL_H', 'ALCOHOL_H', 'OIL_H', 'DAG_H', 'MAG_H', 'ACID_H', 'WATER_H'])
    exp_compositions_np = exp_compositions.to_numpy()
    
    return exp_compositions_np

def load_predicted_data(path):
    
    calculated_data = pl.read_excel(path, engine="calamine")
    calculated_data_np = calculated_data.to_numpy()
    return calculated_data_np

def calculate_RMSE(exp_compositions_np, calculated_data_np):
    results = np.sqrt(np.mean((exp_compositions_np - calculated_data_np)**2, 0)).reshape(1, 16)
    results = pl.DataFrame(results, schema=['FAME/FAEE_L', 'GLYCEROL_L', 'ALCOHOL_L', 'OIL_L', 'DAG_L', 'MAG_L', 'ACID_L', 'WATER_L', 
                                            'FAME/FAEE_H', 'GLYCEROL_H', 'ALCOHOL_H', 'OIL_H', 'DAG_H', 'MAG_H', 'ACID_H', 'WATER_H']) 

    return results

### UNIFAC

In [14]:
exp_compositions_np = load_real_data(r"D:\Juan\proyectos_personales\Maestría\Materias\Tesis\oleosim\ExperimentalData\data\No 47exp\refined_lle_data_v5.xlsx")
calculated_data_np = load_predicted_data(r"D:\Juan\proyectos_personales\Maestría\Materias\Tesis\oleosim\Evaluation\Stochastic_optimization\results_predict_total_UNIFAC_fixed_predict_comps.xlsx")

In [15]:
calculate_RMSE(exp_compositions_np, calculated_data_np)

shape: (1, 16)
┌─────────────┬────────────┬───────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ FAME/FAEE_L ┆ GLYCEROL_L ┆ ALCOHOL_L ┆ OIL_L    ┆ … ┆ DAG_H    ┆ MAG_H    ┆ ACID_H   ┆ WATER_H  │
│ ---         ┆ ---        ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64         ┆ f64        ┆ f64       ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════╪════════════╪═══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 0.351597    ┆ 0.228621   ┆ 0.229849  ┆ 0.101877 ┆ … ┆ 0.000983 ┆ 0.001804 ┆ 0.036306 ┆ 0.097654 │
└─────────────┴────────────┴───────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

#### Unifac Dortmund

In [12]:
exp_compositions_np = load_real_data(r"D:\Juan\proyectos_personales\Maestría\Materias\Tesis\oleosim\ExperimentalData\data\No 47exp\refined_lle_data_v5.xlsx")
calculated_data_np = load_predicted_data(r"D:\Juan\proyectos_personales\Maestría\Materias\Tesis\oleosim\Evaluation\Stochastic_optimization\results_predict_total_diff_evo_adjusted_predict.xlsx")

In [ ]:
calculate_RMSE(exp_compositions_np, calculated_data_np)

shape: (1, 16)
┌─────────────┬────────────┬───────────┬─────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ FAME/FAEE_L ┆ GLYCEROL_L ┆ ALCOHOL_L ┆ OIL_L   ┆ … ┆ DAG_H    ┆ MAG_H    ┆ ACID_H   ┆ WATER_H  │
│ ---         ┆ ---        ┆ ---       ┆ ---     ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64         ┆ f64        ┆ f64       ┆ f64     ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════╪════════════╪═══════════╪═════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 0.249969    ┆ 0.110002   ┆ 0.238798  ┆ 0.24273 ┆ … ┆ 0.005926 ┆ 0.013683 ┆ 0.050591 ┆ 0.118824 │
└─────────────┴────────────┴───────────┴─────────┴───┴──────────┴──────────┴──────────┴──────────┘