In [1]:
import polars as pl
import numpy as np
from sklearn.metrics import root_mean_squared_error

In [2]:
def load_real_data(path):
    exp_data = pl.read_excel(path, engine="calamine")
    exp_compositions = exp_data.select([ 'FAME/FAEE_L', 'GLYCEROL_L', 'ALCOHOL_L', 'OIL_L', 'DAG_L', 'MAG_L', 'ACID_L', 'WATER_L', 'FAME/FAEE_H', 'GLYCEROL_H', 'ALCOHOL_H', 'OIL_H', 'DAG_H', 'MAG_H', 'ACID_H', 'WATER_H'])
    exp_compositions_np = exp_compositions.to_numpy()
    
    return exp_compositions_np

def load_predicted_data(path):
    
    calculated_data = pl.read_excel(path, engine="calamine")
    calculated_data_np = calculated_data.to_numpy()
    return calculated_data_np

def calculate_RMSE(exp_compositions_np, calculated_data_np):
    results = np.sqrt(np.mean((exp_compositions_np - calculated_data_np)**2, 0)).reshape(1, 16)
    results = pl.DataFrame(results, schema=['FAME/FAEE_L', 'GLYCEROL_L', 'ALCOHOL_L', 'OIL_L', 'DAG_L', 'MAG_L', 'ACID_L', 'WATER_L', 
                                            'FAME/FAEE_H', 'GLYCEROL_H', 'ALCOHOL_H', 'OIL_H', 'DAG_H', 'MAG_H', 'ACID_H', 'WATER_H']) 

    return results

### UNIFAC

In [6]:
exp_compositions_np = load_real_data(r"C:\Juan\Maestría\Code\oleosim\ExperimentalData\data\No 47exp\refined_lle_data_v5.xlsx")
calculated_data_np = load_predicted_data(r"C:\Juan\Maestría\Code\oleosim\Evaluation\Stochastic_optimization\results_predict_total_UNIFAC_fixed_predict_1.xlsx")

In [7]:
calculate_RMSE(exp_compositions_np, calculated_data_np)

shape: (1, 16)
┌─────────────┬────────────┬───────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ FAME/FAEE_L ┆ GLYCEROL_L ┆ ALCOHOL_L ┆ OIL_L    ┆ … ┆ DAG_H    ┆ MAG_H    ┆ ACID_H   ┆ WATER_H  │
│ ---         ┆ ---        ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64         ┆ f64        ┆ f64       ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════╪════════════╪═══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 0.351596    ┆ 0.228621   ┆ 0.236405  ┆ 0.148068 ┆ … ┆ 0.000983 ┆ 0.001804 ┆ 0.037399 ┆ 0.139913 │
└─────────────┴────────────┴───────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

#### Unifac Dortmund

In [5]:
exp_compositions_np = load_real_data(r"C:\Juan\Maestría\Code\oleosim\ExperimentalData\data\No 47exp\refined_lle_data_v5.xlsx")
calculated_data_np = load_predicted_data(r"C:\Juan\Maestría\Code\oleosim\Evaluation\Stochastic_optimization\GA\results_predict_total_GA_Run1.xlsx")

In [6]:
calculate_RMSE(exp_compositions_np, calculated_data_np)

shape: (1, 16)
┌─────────────┬────────────┬───────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ FAME/FAEE_L ┆ GLYCEROL_L ┆ ALCOHOL_L ┆ OIL_L    ┆ … ┆ DAG_H    ┆ MAG_H    ┆ ACID_H   ┆ WATER_H  │
│ ---         ┆ ---        ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64         ┆ f64        ┆ f64       ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════╪════════════╪═══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 0.140099    ┆ 0.025981   ┆ 0.135252  ┆ 0.092974 ┆ … ┆ 0.003744 ┆ 0.007585 ┆ 0.010686 ┆ 0.090893 │
└─────────────┴────────────┴───────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [10]:
exp_compositions_np = load_real_data(r"C:\Juan\Maestría\Code\oleosim\ExperimentalData\data\No 47exp\refined_lle_data_v5.xlsx")
calculated_data_np = load_predicted_data(r"C:\Juan\Maestría\Code\oleosim\Evaluation\Stochastic_optimization\GA\results_predict_total_GA_no_iter.xlsx")

In [11]:
calculate_RMSE(exp_compositions_np, calculated_data_np)

shape: (1, 16)
┌─────────────┬────────────┬───────────┬──────────┬───┬──────────┬──────────┬─────────┬──────────┐
│ FAME/FAEE_L ┆ GLYCEROL_L ┆ ALCOHOL_L ┆ OIL_L    ┆ … ┆ DAG_H    ┆ MAG_H    ┆ ACID_H  ┆ WATER_H  │
│ ---         ┆ ---        ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---     ┆ ---      │
│ f64         ┆ f64        ┆ f64       ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64     ┆ f64      │
╞═════════════╪════════════╪═══════════╪══════════╪═══╪══════════╪══════════╪═════════╪══════════╡
│ 0.076722    ┆ 0.015537   ┆ 0.123957  ┆ 0.103804 ┆ … ┆ 0.000982 ┆ 0.001888 ┆ 0.04117 ┆ 0.095057 │
└─────────────┴────────────┴───────────┴──────────┴───┴──────────┴──────────┴─────────┴──────────┘

In [3]:
exp_compositions_np = load_real_data(r"C:\Juan\Maestría\Code\oleosim\ExperimentalData\data\No 47exp\refined_lle_data_v5.xlsx")
calculated_data_np = load_predicted_data(r"C:\Juan\Maestría\Code\oleosim\Evaluation\Stochastic_optimization\GA\results_predict_total_M1GA_no_iter.xlsx")

In [4]:
calculate_RMSE(exp_compositions_np, calculated_data_np)

shape: (1, 16)
┌─────────────┬────────────┬───────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ FAME/FAEE_L ┆ GLYCEROL_L ┆ ALCOHOL_L ┆ OIL_L    ┆ … ┆ DAG_H    ┆ MAG_H    ┆ ACID_H   ┆ WATER_H  │
│ ---         ┆ ---        ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64         ┆ f64        ┆ f64       ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════╪════════════╪═══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 0.08097     ┆ 0.016497   ┆ 0.103635  ┆ 0.087769 ┆ … ┆ 0.000982 ┆ 0.001887 ┆ 0.026705 ┆ 0.113832 │
└─────────────┴────────────┴───────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘